#!/bin/bash

src_dir="/scratch/faculty/kjann/Internship/Jolane_2023/real_OCD_ABCD_Complexity/combined_OCD_ABCD_SWUs/"
dest_dir="/scratch/faculty/kjann/testenv/inputdir/"

files=(
"swusub-NDARINVDYR0ZBCZ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVDYR0ZBCZ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVEP6DZX2M_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVEP6DZX2M_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVKU1J9JFE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVKU1J9JFE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLM6JRR6C_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLM6JRR6C_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVLMXXGG4U_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVLMXXGG4U_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLP57P64D_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLP57P64D_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVLR6BN87U_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLR6BN87U_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVLU2M4RX1_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLU2M4RX1_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVLVJCXFZ6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLVJCXFZ6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVMG9REUL8_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVMG9REUL8_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVNEJ8RBUG_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVNEJ8RBUG_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVNZAAFPBG_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVNZAAFPBG_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVKU1J9JFE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVKU1J9JFE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVP55M5T0X_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVP55M5T0X_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVPZJ5VXTX_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVPZJ5VXTX_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVR06UP6NN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVR06UP6NN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVR76W27PF_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVR76W27PF_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVR81CF71A_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVR81CF71A_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVRE317TA3_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVRE317TA3_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVRFNHTDPM_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVRFNHTDPM_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVRP0XB0ZR_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRP0XB0ZR_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRTD32ZG1_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRTD32ZG1_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVT0R82YDJ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVT0R82YDJ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVT185D4UD_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVT185D4UD_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVCZ89L9CB_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVCZ89L9CB_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVD8MMEU9B_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVD8MMEU9B_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVDHR25U4H_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVDHR25U4H_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVDMMAKV5Y_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVDMMAKV5Y_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVDYNUN0GN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVDYNUN0GN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLN9JCZ56_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVLN9JCZ56_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLRKX5MHU_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVLRKX5MHU_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLRTEWBMH_ses-baselineYear1Arm1_task-rest_run-01_bold.nii" 
"swusub-NDARINVLRTEWBMH_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLW72174Z_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVLW72174Z_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVLX8NH532_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVLX8NH532_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVM02A1YVT_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVM02A1YVT_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVMAXZDNVW_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVMAXZDNVW_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVNJ3MLYLN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVNJ3MLYLN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVP7YTV29E_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVP7YTV29E_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVPATWUAVA_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVPATWUAVA_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVPYD5R8UA_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVPYD5R8UA_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVR27YCM3P_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVR27YCM3P_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVR76W27PF_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVR76W27PF_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVR7WBBFTB_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVR7WBBFTB_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVR7WFN9E7_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVR7WFN9E7_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVR8LMF308_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVR8LMF308_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRAPG65HL_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRAPG65HL_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRCYZ8XZ2_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRCYZ8XZ2_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRF70B79M_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRF70B79M_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRMNMGK77_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRMNMGK77_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRTDZTY9C_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRTDZTY9C_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRXDY2EL7_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRXDY2EL7_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVRXN9H1J6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVRXN9H1J6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVT0R82YDJ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVT0R82YDJ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVT1XD5N8A_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVT1XD5N8A_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVT8JB3RWP_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVT8JB3RWP_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVTAY698CJ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVTAY698CJ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVTCAFT1FE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVTCAFT1FE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii" 
"swusub-NDARINVTDCECT0D_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVTDCECT0D_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVTNV6ZUPK_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVTNV6ZUPK_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVU0EVP5JM_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVU0EVP5JM_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVU390V94C_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVU390V94C_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUA34TJP4_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUA34TJP4_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUDBJ9V2N_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUDBJ9V2N_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUF504K04_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUF504K04_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUFVGYBER_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUFVGYBER_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUGA7X1BC_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUGA7X1BC_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUKDUJYJH_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUKDUJYJH_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUKEHKCA6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUKEHKCA6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUKZ2E83X_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUKZ2E83X_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUUBJL9X5_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUUBJL9X5_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUVW9DC8Y_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUVW9DC8Y_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUXXJ24L8_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUXXJ24L8_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVUY636PFH_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVUY636PFH_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVV104HFJY_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVV104HFJY_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVV4AXRCZ6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVV4AXRCZ6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVV4XY140Z_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVV4XY140Z_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVC130UV5_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVC130UV5_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVF539UBP_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVF539UBP_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVG1MF8K5_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVG1MF8K5_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVGMX0BPT_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVGMX0BPT_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVJ7A5WBE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVJ7A5WBE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVNPA317C_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVNPA317C_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVPZM5DG3_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVPZM5DG3_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVR5BRZPY_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVR5BRZPY_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVRATUJUU_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVRATUJUU_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVRX7WTKX_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVRX7WTKX_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVUD7L4FZ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVUD7L4FZ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVXJBWAPD_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVXJBWAPD_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVXN3Y1F1_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVXN3Y1F1_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVVZGWFC56_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVVZGWFC56_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW03T0R3Y_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW03T0R3Y_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW0VV53Y4_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW0VV53Y4_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW17VYJ0L_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW17VYJ0L_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW1BFMH04_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW1BFMH04_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW3FWG7L0_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW3FWG7L0_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW3LL7MG1_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW3LL7MG1_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVW7D6ATVH_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVW7D6ATVH_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWAC9RH98_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWAC9RH98_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWAVA878R_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWAVA878R_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWCB3M1XX_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWCB3M1XX_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWCG2L6JG_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWCG2L6JG_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWEJMEVJN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWEJMEVJN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWEV9M1BE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWEV9M1BE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWGARRD3J_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWGARRD3J_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWHXE421P_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWHXE421P_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWLNTC8GU_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWLNTC8GU_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWMBFRZWJ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWMBFRZWJ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWV30VA2P_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWV30VA2P_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWVFZTJX6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWVFZTJX6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWVW0NNAD_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWVW0NNAD_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVWZ5MKFYM_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVWZ5MKFYM_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX362LD83_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX362LD83_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX3GM1J59_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX3GM1J59_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX3MF6X7B_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX3MF6X7B_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX45DG8HN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX45DG8HN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX7KKFJ5E_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX7KKFJ5E_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVX8AY31TT_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVX8AY31TT_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXAF2R3YX_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXAF2R3YX_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXBNU804E_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXBNU804E_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXGT4UWYN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXGT4UWYN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXHXZ933C_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXHXZ933C_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXJ2454AG_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXJ2454AG_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXRBWGD7W_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXRBWGD7W_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXUKXXT12_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXUKXXT12_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXWXUUU18_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXWXUUU18_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVXZKP1VEC_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVXZKP1VEC_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVY41681B5_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVY41681B5_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVY8EW1EXZ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVY8EW1EXZ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVY92TEZW6_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVY92TEZW6_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYE7B0PFZ_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYE7B0PFZ_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYEMDCKWK_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYEMDCKWK_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYJPCD59K_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYJPCD59K_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYKVPYY2M_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYKVPYY2M_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYWEY5YL9_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYWEY5YL9_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVYXVML8U8_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVYXVML8U8_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZ0FPZPLP_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZ0FPZPLP_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZ4X8D1A7_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZ4X8D1A7_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZ6Z9DP4H_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZ6Z9DP4H_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZEV3PCPL_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZEV3PCPL_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZH1A3UUP_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZH1A3UUP_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZWRJXNHE_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZWRJXNHE_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"
"swusub-NDARINVZX24TGXN_ses-baselineYear1Arm1_task-rest_run-01_bold.nii"
"swusub-NDARINVZX24TGXN_ses-baselineYear1Arm1_task-rest_run-02_bold.nii"  
)

for file in "${files[@]}"; do
    echo "Checking file: ${src_dir}${file}"
    if [ -f "${src_dir}${file}" ]; then
        cp "${src_dir}${file}" "${dest_dir}"
        if [ $? -eq 0 ]; then
            echo "Copied: ${file}"
        else
            echo "Failed to copy: ${file}"
        fi
    else
        echo "File does not exist: ${src_dir}${file}"
    fi
done






























